repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

  - repo: https://github.com/ansible/ansible-lint.git
    rev: v4.3.5
    hooks:
      - id: ansible-lint
        always_run: true
        pass_filenames: false
        verbose: true
        entry: env ANSIBLE_LIBRARY=./library ansible-lint --force-color -p -v .
        additional_dependencies:
          - 'ansible<2.10'
