---
roles:
# httpd is added to test the connection. (see `molecule/default/verify.yml`)
  - name: robertdebock.bootstrap
  - name: robertdebock.buildtools
  - name: robertdebock.core_dependencies
  - name: robertdebock.epel
  - name: robertdebock.httpd
  - name: robertdebock.openssl
  - name: robertdebock.python_pip
