---
- robertdebock.bootstrap
- robertdebock.core_dependencies
- robertdebock.buildtools
- robertdebock.epel
# httpd is added to test the connection. (see `molecule/default/verify.yml`)
- robertdebock.httpd
- robertdebock.python_pip
- robertdebock.openssl
