---
# tasks file for haproxy
- name: load default variables
  include_vars:
    file: default.yml

- name: load os-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - default.yml

- name: install software
  package:
    name: haproxy

- name: start and enable software
  service:
    name: haproxy
    state: started
    enabled: yes
