---
# tasks file for haproxy
- name: load default variables
  include_vars:
    file: default.yml

- name: load os-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - default.yml

- name: install software
  package:
    name: haproxy

- name: configure software
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    validate: haproxy -c -f %s
  notify:
    - restart software

- name: add haproxy_stats_port to http_port_t selinux type
  seport:
    ports: "{{ haproxy_stats_port }}"
    proto: tcp
    setype: http_port_t
    state: present
  when:
    - haproxy_stats_port is defined
    - ansible_selinux.status is defined
    - ansible_selinux.status == "enabled"

- name: start and enable software
  service:
    name: haproxy
    state: started
    enabled: yes
  when:
    - ansible_virtualization_type != "docker"
