---
- name: Verify
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    _netcat_package:
      default: nc
      Alpine: netcat-openbsd
      Debian: netcat
      Suse: netcat-openbsd
    netcat_package: "{{ _netcat_package[ansible_os_family] | default(_netcat_package['default']) }}"

  tasks:
    - name: install testing requirements
      package:
        name: "{{ netcat_package }}"
        state: present
      notify:
        - uninstall testing requirements

    - name: check if ports responds
      ansible.builtin.wait_for:
        port: "{{ item }}"
      loop:
        - 80
        - 443

    - name: check of content can be retrieved
      ansible.builtin.uri:
        url: "{{ item }}"
        validate_certs: no
        status_code:
          - 200
          - 403
      loop:
        - "http://localhost/"
        - "https://localhost/"

    - name: check if stats are available
      ansible.builtin.shell:
        cmd: echo "show stat" | netcat -U /var/lib/haproxy/stats
      changed_when: no

  handlers:
    - name: uninstall testing requirements
      package:
        name: "{{ netcat_package }}"
        state: absent
